### PR TITLE
ola :D

### PR DESCRIPTION
**Pull request by aaryswastaken**
Implementez `handleSpl` avec ce que vous voulez

### CODE REVIEW

**Comment by aaryswastaken** [comment]
image

ac de-offset + gain (non inverting)

**Comment by aaryswastaken** [comment]
(green mic output, red adc input)

**Comment by aaryswastaken** [comment]
(the adc input will be 0-5V clamped because of the asymetrical power rails)

**Review by Byllie — APPROVED** [review]

**Comment by Byllie** [comment]
Lgtm

**Pull request merged**
